# Generated by Django 5.1.1 on 2024-10-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user_name',
            new_name='author',
        ),
    ]
