# Generated by Django 5.1.1 on 2024-11-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_city_customuser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='users/placeholderUserImage.jpg', upload_to='users/'),
        ),
    ]
