# Generated by Django 5.1.1 on 2024-10-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_shortdescripiton'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='prepTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='difficulty',
            field=models.ManyToManyField(related_name='products', to='api.difficulty'),
        ),
    ]
