# Generated by Django 5.1.1 on 2024-11-01 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_difficulty_product_preptime_product_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shortDescripiton',
            new_name='shortDescription',
        ),
    ]
